import streamlit as st
import asyncio
import os
from datetime import datetime
import json

# Must be first Streamlit command
st.set_page_config(
    page_title="AI Competitor Intelligence",
    page_icon="🔍",
    layout="wide",
    initial_sidebar_state="expanded"
)

# ========================================
# HELPER FUNCTIONS (Define BEFORE usage)
# ========================================

def generate_text_report(result: dict, company_name: str) -> str:
    """Generate text format report"""
    
    synthesis = result.get('synthesis', {})
    swot = synthesis.get('swot_analysis', {})
    
    report = f"""
{'='*60}
COMPETITOR INTELLIGENCE REPORT
{'='*60}

Company: {company_name}
Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

{'='*60}
EXECUTIVE SUMMARY
{'='*60}

{synthesis.get('executive_summary', 'N/A')}

{'='*60}
KEY METRICS
{'='*60}

Competitive Score: {synthesis.get('competitive_score', 0)}/100
Financial Health: {synthesis.get('financial_health', {}).get('health_score', 0)}/100
Product-Market Fit: {synthesis.get('product_analysis', {}).get('product_market_fit_score', 0)}/100

{'='*60}
SWOT ANALYSIS
{'='*60}

STRENGTHS:
{chr(10).join(f'  • {s}' for s in swot.get('strengths', ['N/A']))}

WEAKNESSES:
{chr(10).join(f'  • {w}' for w in swot.get('weaknesses', ['N/A']))}

OPPORTUNITIES:
{chr(10).join(f'  • {o}' for o in swot.get('opportunities', ['N/A']))}

THREATS:
{chr(10).join(f'  • {t}' for t in swot.get('threats', ['N/A']))}

{'='*60}
STRATEGIC RECOMMENDATIONS
{'='*60}

{chr(10).join(f'{i}. {r}' for i, r in enumerate(synthesis.get('strategic_recommendations', ['N/A']), 1))}

{'='*60}
END OF REPORT
{'='*60}

Generated by AI Competitor Intelligence
Powered by open-source AI (Groq, LangChain, Streamlit)
"""
    
    return report


def display_results(result: dict, company_name: str):
    """Display research results in structured format"""
    
    synthesis = result.get('synthesis', {})
    
    if not synthesis:
        st.warning("⚠️ Synthesis data not available")
        return
    
    # Executive Summary
    st.subheader("📋 Executive Summary")
    summary = synthesis.get('executive_summary', 'No summary available')
    st.info(summary)
    
    st.markdown("---")
    
    # Key Metrics Row
    st.subheader("📊 Key Metrics")
    col1, col2, col3 = st.columns(3)
    
    with col1:
        score = synthesis.get('competitive_score', 0)
        st.metric(
            "Competitive Score",
            f"{score}/100",
            help="Overall competitive strength in the market"
        )
    
    with col2:
        health = synthesis.get('financial_health', {})
        health_score = health.get('health_score', 0)
        st.metric(
            "Financial Health",
            f"{health_score}/100",
            help="Financial stability and growth trajectory"
        )
    
    with col3:
        product = synthesis.get('product_analysis', {})
        pmf = product.get('product_market_fit_score', 0)
        st.metric(
            "Product-Market Fit",
            f"{pmf}/100",
            help="How well the product meets market needs"
        )
    
    st.markdown("---")
    
    # Company Overview
    st.subheader("🏢 Company Overview")
    overview = synthesis.get('company_overview', {})
    
    if overview:
        col1, col2 = st.columns(2)
        
        with col1:
            st.markdown("**Background**")
            st.write(overview.get('background', 'N/A'))
        
        with col2:
            st.markdown("**Market Position**")
            st.write(overview.get('market_position', 'N/A'))
        
        st.markdown("**Size & Scale**")
        st.write(overview.get('size_and_scale', 'N/A'))
    
    st.markdown("---")
    
    # SWOT Analysis
    st.subheader("📊 SWOT Analysis")
    swot = synthesis.get('swot_analysis', {})
    
    col1, col2 = st.columns(2)
    
    with col1:
        # Strengths
        with st.expander("💪 **Strengths**", expanded=True):
            strengths = swot.get('strengths', [])
            if strengths:
                for s in strengths:
                    st.markdown(f"✅ {s}")
            else:
                st.write("_No data available_")
        
        # Opportunities
        with st.expander("🎯 **Opportunities**", expanded=True):
            opps = swot.get('opportunities', [])
            if opps:
                for o in opps:
                    st.markdown(f"🔹 {o}")
            else:
                st.write("_No data available_")
    
    with col2:
        # Weaknesses
        with st.expander("⚠️ **Weaknesses**", expanded=True):
            weaknesses = swot.get('weaknesses', [])
            if weaknesses:
                for w in weaknesses:
                    st.markdown(f"⚠️ {w}")
            else:
                st.write("_No data available_")
        
        # Threats
        with st.expander("🚨 **Threats**", expanded=True):
            threats = swot.get('threats', [])
            if threats:
                for t in threats:
                    st.markdown(f"⚡ {t}")
            else:
                st.write("_No data available_")
    
    st.markdown("---")
    
    # Product Analysis
    st.subheader("🎨 Product & Offering Analysis")
    product_analysis = synthesis.get('product_analysis', {})
    
    if product_analysis:
        col1, col2 = st.columns(2)
        
        with col1:
            st.markdown("**Core Offerings**")
            st.write(product_analysis.get('core_offerings', 'N/A'))
            
            st.markdown("**Pricing Strategy**")
            st.write(product_analysis.get('pricing_strategy', 'N/A'))
        
        with col2:
            st.markdown("**Key Differentiators**")
            differentiators = product_analysis.get('differentiators', [])
            if differentiators:
                for d in differentiators:
                    st.markdown(f"• {d}")
            else:
                st.write("_No data available_")
    
    st.markdown("---")
    
    # Financial Health
    st.subheader("💰 Financial Health Assessment")
    financial = synthesis.get('financial_health', {})
    
    if financial:
        st.write(f"**Status:** {financial.get('status', 'Unknown')}")
        st.write(f"**Growth Trajectory:** {financial.get('growth_trajectory', 'Unknown')}")
        
        # Health score visual
        health_pct = financial.get('health_score', 50)
        st.progress(health_pct / 100)
        st.caption(f"Financial Health Score: {health_pct}/100")
    
    st.markdown("---")
    
    # Strategic Recommendations
    st.subheader("💡 Strategic Recommendations")
    recommendations = synthesis.get('strategic_recommendations', [])
    
    if recommendations:
        for i, rec in enumerate(recommendations, 1):
            st.markdown(f"**{i}.** {rec}")
    else:
        st.write("_No recommendations available_")
    
    st.markdown("---")
    
    # Export Section
    st.subheader("💾 Export & Download")
    
    col1, col2, col3 = st.columns(3)
    
    with col1:
        # JSON download
        json_data = json.dumps(result, indent=2)
        st.download_button(
            label="📥 Download JSON",
            data=json_data,
            file_name=f"{company_name.replace(' ', '_')}_research.json",
            mime="application/json",
            use_container_width=True,
            key=f"download_json_{company_name.replace(' ', '_')}"
        )
    
    with col2:
        # Text summary
        text_summary = generate_text_report(result, company_name)
        st.download_button(
            label="📄 Download Report (TXT)",
            data=text_summary,
            file_name=f"{company_name.replace(' ', '_')}_report.txt",
            mime="text/plain",
            use_container_width=True,
            key=f"download_txt_{company_name.replace(' ', '_')}"
        )
    
    with col3:
        # Copy to clipboard (JSON)
        if st.button("📋 Copy JSON", use_container_width=True, key=f"copy_json_{company_name.replace(' ', '_')}"):
            st.code(json_data, language="json")
            st.success("JSON displayed above - use your browser to copy")


# ========================================
# CHECK API KEY (from Streamlit Secrets)
# ========================================

# Check if API key exists in secrets
if "GROQ_API_KEY" not in st.secrets:
    st.error("🔑 **API Key Not Configured**")
    st.markdown("""
    ### Setup Required
    
    The Groq API key is missing from Streamlit Secrets.
    
    **To fix this:**
    1. Go to your Streamlit Cloud dashboard
    2. Click on your app
    3. Go to **Settings** → **Secrets**
    4. Add this:
    ```toml
    GROQ_API_KEY = "your_groq_api_key_here"
    ```
    5. Get a free API key at [console.groq.com](https://console.groq.com)
    6. Save and reboot the app
    """)
    st.stop()

# Set environment variable from secrets
os.environ["GROQ_API_KEY"] = st.secrets["GROQ_API_KEY"]

# ========================================
# MAIN APP UI
# ========================================

# Custom CSS
st.markdown("""
<style>
    .main-header {
        font-size: 3rem;
        font-weight: bold;
        background: linear-gradient(90deg, #2c5aa0 0%, #1e3a8a 100%);
        -webkit-background-clip: text;
        -webkit-text-fill-color: transparent;
        margin-bottom: 0.5rem;
    }
    .subtitle {
        color: #666;
        font-size: 1.2rem;
        margin-bottom: 2rem;
    }
    .metric-card {
        background: #f0f2f6;
        padding: 1rem;
        border-radius: 0.5rem;
        border-left: 4px solid #2c5aa0;
    }
    .stDownloadButton button {
        width: 100%;
    }
</style>
""", unsafe_allow_html=True)

# Title
st.markdown('<h1 class="main-header">🔍 AI Competitor Intelligence</h1>', unsafe_allow_html=True)
st.markdown('<p class="subtitle">Autonomous market research powered by 100% open-source AI</p>', unsafe_allow_html=True)
st.markdown("---")

# Sidebar Configuration
with st.sidebar:
    st.header("⚙️ Settings")
    
    # API Status (no password input!)
    st.success("🔑 API Key: Configured ✅")
    
    st.markdown("---")
    
    # Research settings
    st.subheader("Research Settings")
    
    depth_option = st.selectbox(
        "Analysis Depth",
        [
            "Quick Analysis (2-3 min)",
            "Standard Analysis (5-7 min)",
            "Deep Analysis (10-15 min)"
        ],
        index=1,
        help="Deeper analysis takes longer but provides more insights"
    )
    
    depth_mapping = {
        "Quick Analysis (2-3 min)": "quick",
        "Standard Analysis (5-7 min)": "standard",
        "Deep Analysis (10-15 min)": "deep"
    }
    depth = depth_mapping[depth_option]
    
    st.markdown("---")
    
    # ✅ NEW: Model Strategy Selector
    st.subheader("🤖 AI Model Strategy")
    
    model_strategy = st.selectbox(
        "Model Selection",
        [
            "🚀 Auto-Optimize (Recommended)",
            "⚡ Speed Priority",
            "🧠 Quality Priority",
            "⚖️ Balanced",
        ],
        index=0,
        help="Auto-Optimize uses the best model for each task automatically"
    )
    
    # Show what models will be used
    if model_strategy == "🚀 Auto-Optimize (Recommended)":
        with st.expander("ℹ️ Models Used", expanded=False):
            st.markdown("""
            **Intelligent Multi-Model Approach:**
            - 📊 Data Extraction: `llama-3.3-70b-versatile`
            - 💭 Strategic Analysis: `llama-3.1-70b-specdec`
            - ⚡ Quick Tasks: `llama-3.3-70b-versatile`
            
            **Benefits:**
            - ✅ Best quality for each task
            - ✅ Optimal speed/quality balance
            - ✅ Still 100% free!
            """)
    elif model_strategy == "⚡ Speed Priority":
        with st.expander("ℹ️ Models Used", expanded=False):
            st.markdown("""
            **All Tasks:** `llama-3.3-70b-versatile`
            
            **Benefits:**
            - ⚡ Fastest results
            - ✅ Good quality
            - ✅ 100% free!
            """)
    elif model_strategy == "🧠 Quality Priority":
        with st.expander("ℹ️ Models Used", expanded=False):
            st.markdown("""
            **All Tasks:** `llama-3.1-70b-specdec`
            
            **Benefits:**
            - 🎯 Highest quality
            - 🧠 Best reasoning
            - ✅ 100% free!
            """)
    elif model_strategy == "⚖️ Balanced":
        with st.expander("ℹ️ Models Used", expanded=False):
            st.markdown("""
            **All Tasks:** `llama-3.3-70b-versatile`
            
            **Benefits:**
            - ⚖️ Speed + Quality
            - ✅ Great all-around
            - ✅ 100% free!
            """)
    
    st.markdown("---")
    
    # Stats (if available)
    if 'latest_result' in st.session_state:
        st.subheader("📊 Quick Stats")
        result = st.session_state['latest_result']
        synthesis = result.get('synthesis', {})
        
        st.metric("Competitive Score", f"{synthesis.get('competitive_score', 0)}/100")
        st.metric("Financial Health", f"{synthesis.get('financial_health', {}).get('health_score', 0)}/100")
    
    st.markdown("---")
    
    # Info section
    with st.expander("ℹ️ About This Tool"):
        st.markdown("""
        **What it does:**
        - Researches company websites
        - Analyzes social media presence
        - Evaluates financial health
        - Assesses product offerings
        - Generates strategic insights
        
        **Technology:**
        - LLM: Groq (Llama 3.1 70B)
        - Framework: LangChain
        - 100% Open Source
        
        **Privacy:**
        - API key stored securely in Streamlit Secrets
        - No data stored on our servers
        - All processing via Groq API
        """)
    
    st.markdown("---")
    st.caption("Built with ❤️ using open-source AI")

# Main content tabs
tab1, tab2, tab3 = st.tabs(["🎯 New Research", "📊 Latest Results", "📖 Examples"])

# TAB 1: New Research
with tab1:
    st.header("Start New Competitor Research")
    
    col1, col2 = st.columns([3, 1])
    
    with col1:
        company_name = st.text_input(
            "Company Name",
            placeholder="e.g., Stripe, Notion, Figma, OpenAI, Shopify",
            help="Enter the exact company name for best results"
        )
    
    with col2:
        st.write("")  # Spacing
        st.write("")  # Spacing
        start_research = st.button(
            "🚀 Start Research",
            type="primary",
            use_container_width=True
        )
    
    # Example companies
    st.caption("**Try these companies:** Stripe • Notion • Figma • Linear • Vercel • Supabase • Replicate")
    
    if start_research:
        if not company_name or len(company_name) < 2:
            st.error("❌ Please enter a valid company name")
        else:
            # Import orchestrator (after API key is set)
            try:
                from agents.orchestrator import run_research
                
                with st.spinner(f"🔍 Researching {company_name}..."):
                    # Progress tracking
                    progress_bar = st.progress(0)
                    status_container = st.empty()
                    
                    def progress_callback(progress: int, status: str):
                        progress_bar.progress(progress / 100)
                        status_container.info(f"**Status:** {status}")
                    
                    # Run research
                    try:
                        # Map UI strategy to internal code
                        strategy_mapping = {
                            "🚀 Auto-Optimize (Recommended)": "auto",
                            "⚡ Speed Priority": "speed",
                            "🧠 Quality Priority": "quality",
                            "⚖️ Balanced": "balanced"
                        }
                        
                        result = asyncio.run(run_research(
                            company_name=company_name,
                            depth=depth,
                            model_strategy=strategy_mapping[model_strategy],  # ✅ ADDED
                            progress_callback=progress_callback
                        ))
                        
                        # Store in session state
                        st.session_state['latest_result'] = result
                        st.session_state['latest_company'] = company_name
                        st.session_state['research_timestamp'] = datetime.now()
                        
                        # Clear progress
                        progress_bar.empty()
                        status_container.empty()
                        
                        st.success(f"✅ Research complete for **{company_name}**!")
                        
                        # Display results
                        st.markdown("---")
                        display_results(result, company_name)
                        
                    except Exception as e:
                        st.error(f"❌ Research failed: {str(e)}")
                        st.exception(e)
                        
            except ImportError as e:
                st.error(f"❌ Failed to import research modules: {e}")
                st.info("Please make sure all agent files are uploaded correctly.")

# TAB 2: Latest Results
with tab2:
    st.header("📊 Latest Research Results")
    
    if 'latest_result' in st.session_state:
        company = st.session_state.get('latest_company', 'Unknown')
        result = st.session_state['latest_result']
        timestamp = st.session_state.get('research_timestamp', datetime.now())
        
        st.info(f"📅 **Company:** {company} | **Generated:** {timestamp.strftime('%Y-%m-%d %H:%M:%S')}")
        
        display_results(result, company)
    else:
        st.info("👈 Run a research from the **New Research** tab first")
        
        st.markdown("""
        ### What you'll get:
        
        - 📋 **Executive Summary** - Key insights at a glance
        - 📊 **SWOT Analysis** - Strengths, Weaknesses, Opportunities, Threats
        - 💰 **Financial Health** - Funding, growth, stability assessment
        - 🎨 **Product Analysis** - Features, pricing, market fit
        - 💡 **Strategic Recommendations** - Actionable next steps
        - 📥 **Export Options** - Download as JSON or TXT
        """)

# TAB 3: Examples
with tab3:
    st.header("📖 Example Companies & Use Cases")
    
    col1, col2 = st.columns(2)
    
    with col1:
        st.subheader("🚀 Tech Startups")
        st.markdown("""
        **Great for competitive analysis:**
        - **Stripe** - Payment processing
        - **Notion** - Productivity & workspace
        - **Figma** - Design collaboration
        - **Linear** - Issue tracking
        - **Vercel** - Web deployment
        - **Supabase** - Backend-as-a-service
        """)
        
        st.subheader("🤖 AI Companies")
        st.markdown("""
        **Understand AI landscape:**
        - **OpenAI** - GPT models
        - **Anthropic** - Claude AI
        - **Hugging Face** - AI community
        - **Replicate** - AI model hosting
        - **Stability AI** - Image generation
        """)
    
    with col2:
        st.subheader("💼 B2B SaaS")
        st.markdown("""
        **Enterprise software analysis:**
        - **Salesforce** - CRM leader
        - **HubSpot** - Marketing automation
        - **Intercom** - Customer messaging
        - **Zendesk** - Customer support
        - **Slack** - Team communication
        """)
        
        st.subheader("🛒 E-commerce")
        st.markdown("""
        **E-commerce platforms:**
        - **Shopify** - Online stores
        - **WooCommerce** - WordPress commerce
        - **BigCommerce** - Enterprise e-commerce
        - **Square** - Point of sale
        """)
    
    st.markdown("---")
    
    st.subheader("💡 Best Practices")
    st.markdown("""
    **For best results:**
    
    1. **Use exact company names** - "Stripe" not "Stripe Inc"
    2. **Start with Standard depth** - Good balance of speed and detail
    3. **Research competitors together** - Compare 2-3 companies
    4. **Download results** - Save as JSON for later analysis
    5. **Verify critical data** - LLM insights should be verified for business decisions
    
    **What to do with results:**
    - 📊 Competitive positioning analysis
    - 💰 Investor research and due diligence
    - 🎯 Market entry strategy
    - 📈 Feature comparison for product roadmap
    - 💼 Sales intelligence and competitive battlecards
    """)

# Footer
st.markdown("---")
st.markdown("""
<div style='text-align: center; color: #666; padding: 2rem 0;'>
    <p><strong>AI Competitor Intelligence</strong></p>
    <p>Powered by Groq • LangChain • Streamlit</p>
    <p>100% Open Source • No Data Stored • Privacy First</p>
</div>
""", unsafe_allow_html=True)
