import streamlit as st
import asyncio
import os
from datetime import datetime
import json
import uuid

st.set_page_config(
    page_title="AI Competitor Intelligence",
    page_icon="🔍",
    layout="wide",
    initial_sidebar_state="expanded"
)

# ========================================
# HELPER FUNCTIONS
# ========================================

def generate_text_report(result: dict, company_name: str) -> str:
    """Generate text format report"""
    
    synthesis = result.get('synthesis', {})
    swot = synthesis.get('swot_analysis', {})
    
    report = f"""
{'='*60}
COMPETITOR INTELLIGENCE REPORT
{'='*60}

Company: {company_name}
Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

{'='*60}
EXECUTIVE SUMMARY
{'='*60}

{synthesis.get('executive_summary', 'N/A')}

{'='*60}
KEY METRICS
{'='*60}

Competitive Score: {synthesis.get('competitive_score', 0)}/100
Financial Health: {synthesis.get('financial_health', {}).get('health_score', 0)}/100
Product-Market Fit: {synthesis.get('product_analysis', {}).get('product_market_fit_score', 0)}/100

{'='*60}
SWOT ANALYSIS
{'='*60}

STRENGTHS:
{chr(10).join(f'  • {s}' for s in swot.get('strengths', ['N/A']))}

WEAKNESSES:
{chr(10).join(f'  • {w}' for w in swot.get('weaknesses', ['N/A']))}

OPPORTUNITIES:
{chr(10).join(f'  • {o}' for o in swot.get('opportunities', ['N/A']))}

THREATS:
{chr(10).join(f'  • {t}' for t in swot.get('threats', ['N/A']))}

{'='*60}
STRATEGIC RECOMMENDATIONS
{'='*60}

{chr(10).join(f'{i}. {r}' for i, r in enumerate(synthesis.get('strategic_recommendations', ['N/A']), 1))}

{'='*60}
Generated by AI Competitor Intelligence
"""
    
    return report


def display_results(result: dict, company_name: str, context: str = "main"):
    """Display research results"""
    
    synthesis = result.get('synthesis', {})
    
    if not synthesis:
        st.warning("⚠️ Synthesis data not available")
        return
    
    unique_key = f"{context}_{uuid.uuid4().hex[:8]}"
    
    # Executive Summary
    st.subheader("📋 Executive Summary")
    st.info(synthesis.get('executive_summary', 'No summary available'))
    
    st.markdown("---")
    
    # Key Metrics
    st.subheader("📊 Key Metrics")
    col1, col2, col3 = st.columns(3)
    
    with col1:
        st.metric("Competitive Score", f"{synthesis.get('competitive_score', 0)}/100")
    
    with col2:
        health = synthesis.get('financial_health', {})
        st.metric("Financial Health", f"{health.get('health_score', 0)}/100")
    
    with col3:
        product = synthesis.get('product_analysis', {})
        st.metric("Product-Market Fit", f"{product.get('product_market_fit_score', 0)}/100")
    
    st.markdown("---")
    
    # Company Overview
    st.subheader("🏢 Company Overview")
    overview = synthesis.get('company_overview', {})
    
    if overview:
        col1, col2 = st.columns(2)
        with col1:
            st.markdown("**Background**")
            st.write(overview.get('background', 'N/A'))
        with col2:
            st.markdown("**Market Position**")
            st.write(overview.get('market_position', 'N/A'))
    
    st.markdown("---")
    
    # SWOT Analysis
    st.subheader("📊 SWOT Analysis")
    swot = synthesis.get('swot_analysis', {})
    
    col1, col2 = st.columns(2)
    
    with col1:
        with st.expander("💪 **Strengths**", expanded=True):
            for s in swot.get('strengths', []):
                st.markdown(f"✅ {s}")
        
        with st.expander("🎯 **Opportunities**", expanded=True):
            for o in swot.get('opportunities', []):
                st.markdown(f"🔹 {o}")
    
    with col2:
        with st.expander("⚠️ **Weaknesses**", expanded=True):
            for w in swot.get('weaknesses', []):
                st.markdown(f"⚠️ {w}")
        
        with st.expander("🚨 **Threats**", expanded=True):
            for t in swot.get('threats', []):
                st.markdown(f"⚡ {t}")
    
    st.markdown("---")
    
    # Product Analysis
    st.subheader("🎨 Product Analysis")
    product_analysis = synthesis.get('product_analysis', {})
    
    if product_analysis:
        st.write(f"**Core Offerings:** {product_analysis.get('core_offerings', 'N/A')}")
        st.write(f"**Pricing Strategy:** {product_analysis.get('pricing_strategy', 'N/A')}")
    
    st.markdown("---")
    
    # Strategic Recommendations
    st.subheader("💡 Strategic Recommendations")
    for i, rec in enumerate(synthesis.get('strategic_recommendations', []), 1):
        st.markdown(f"**{i}.** {rec}")
    
    st.markdown("---")
    
    # Export
    st.subheader("💾 Export")
    
    col1, col2 = st.columns(2)
    
    with col1:
        json_data = json.dumps(result, indent=2)
        st.download_button(
            "📥 Download JSON",
            json_data,
            f"{company_name.replace(' ', '_')}_research.json",
            "application/json",
            use_container_width=True,
            key=f"json_{unique_key}"
        )
    
    with col2:
        text_summary = generate_text_report(result, company_name)
        st.download_button(
            "📄 Download Report",
            text_summary,
            f"{company_name.replace(' ', '_')}_report.txt",
            "text/plain",
            use_container_width=True,
            key=f"txt_{unique_key}"
        )


# Check API key
if "GROQ_API_KEY" not in st.secrets:
    st.error("🔑 **API Key Not Configured**")
    st.stop()

os.environ["GROQ_API_KEY"] = st.secrets["GROQ_API_KEY"]

# ========================================
# MAIN UI
# ========================================

st.markdown("""
<style>
    .main-header {
        font-size: 3rem;
        font-weight: bold;
        background: linear-gradient(90deg, #2c5aa0 0%, #1e3a8a 100%);
        -webkit-background-clip: text;
        -webkit-text-fill-color: transparent;
    }
</style>
""", unsafe_allow_html=True)

st.markdown('<h1 class="main-header">🔍 AI Competitor Intelligence</h1>', unsafe_allow_html=True)
st.markdown("*Autonomous market research powered by AI*")
st.markdown("---")

# ========================================
# SIDEBAR WITH MODEL SELECTOR
# ========================================

with st.sidebar:
    st.header("⚙️ Settings")
    
    st.success("🔑 API Key: Configured ✅")
    
    st.markdown("---")
    
    # Research Depth
    st.subheader("Research Settings")
    
    depth_option = st.selectbox(
        "Analysis Depth",
        ["Quick (2-3 min)", "Standard (5-7 min)", "Deep (10-15 min)"],
        index=1,
    )
    
    depth_mapping = {
        "Quick (2-3 min)": "quick",
        "Standard (5-7 min)": "standard",
        "Deep (10-15 min)": "deep"
    }
    depth = depth_mapping[depth_option]
    
    st.markdown("---")
    
    # ✅ MODEL SELECTOR (User Control)
    st.subheader("🤖 AI Model Selection")
    
    model_strategy = st.selectbox(
        "Choose Model Strategy",
        [
            "🚀 Auto-Optimize (Recommended)",
            "⚡ Llama 3.3 70B (Fast & Balanced)",
            "🧠 Llama 3.3 70B (Quality Focus)",
            "🔄 Mixtral 8x7B (Alternative)",
        ],
        index=0,
        help="Auto-Optimize uses the best model for each task. Other options use that model for all tasks."
    )
    
    # Show model details
    with st.expander("ℹ️ Model Details", expanded=False):
        if model_strategy == "🚀 Auto-Optimize (Recommended)":
            st.markdown("""
            **Intelligent Multi-Model Routing:**
            - Data extraction → Llama 3.3 70B
            - Strategic analysis → Llama 3.3 70B  
            - Quick tasks → Llama 3.3 70B
            
            **Benefits:**
            - ✅ Best quality per task
            - ✅ Optimal speed
            - ✅ Automatic fallback
            """)
        
        elif model_strategy == "⚡ Llama 3.3 70B (Fast & Balanced)":
            st.markdown("""
            **Single Model: Llama 3.3 70B**
            
            **Characteristics:**
            - ⚡ Very fast (500+ tokens/sec)
            - ⭐ Great quality
            - 🎯 Best all-around choice
            
            **Use when:**
            - You want consistent speed
            - You need reliable results
            """)
        
        elif model_strategy == "🧠 Llama 3.3 70B (Quality Focus)":
            st.markdown("""
            **Single Model: Llama 3.3 70B**
            
            **Optimized for:**
            - 🧠 Deep reasoning
            - 📊 Complex analysis
            - 💎 Strategic insights
            
            **Use when:**
            - Quality > Speed
            - Strategic decisions needed
            """)
        
        elif model_strategy == "🔄 Mixtral 8x7B (Alternative)":
            st.markdown("""
            **Single Model: Mixtral 8x7B**
            
            **Characteristics:**
            - 📚 32K token context
            - ⚡ Fast
            - 🔄 Good alternative
            
            **Use when:**
            - Need long context
            - Llama 3.3 has issues
            """)
    
    # Show current model status
    st.caption("💡 **Tip:** Try Auto-Optimize first. Switch if you encounter issues.")
    
    st.markdown("---")
    
    # Quick stats
    if 'latest_result' in st.session_state:
        st.subheader("📊 Last Research")
        st.write(f"**Company:** {st.session_state.get('latest_company', 'N/A')}")
        
        synthesis = st.session_state['latest_result'].get('synthesis', {})
        score = synthesis.get('competitive_score', 0)
        st.metric("Score", f"{score}/100")
    
    st.markdown("---")
    
    with st.expander("ℹ️ About"):
        st.markdown("""
        **AI Competitor Intelligence**
        
        Autonomous research system that analyzes:
        - Company websites
        - Social presence  
        - Financial health
        - Product offerings
        - Strategic positioning
        
        **100% Free & Open Source**
        """)
    
    st.markdown("---")
    st.caption("Built with ❤️ using open-source AI")

# ========================================
# MAIN TABS
# ========================================

tab1, tab2, tab3 = st.tabs(["🎯 New Research", "📊 Latest Results", "📖 Examples"])

with tab1:
    st.header("Start New Competitor Research")
    
    col1, col2 = st.columns([3, 1])
    
    with col1:
        company_name = st.text_input(
            "Company Name",
            placeholder="e.g., Stripe, Notion, Figma",
        )
    
    with col2:
        st.write("")
        st.write("")
        start_research = st.button("🚀 Start Research", type="primary", use_container_width=True)
    
    st.caption("**Try:** Stripe • Notion • Figma • Linear • Vercel")
    
    if start_research:
        if not company_name or len(company_name) < 2:
            st.error("❌ Please enter a company name")
        else:
            try:
                from agents.orchestrator import run_research
                
                # Map UI selection to internal model strategy
                strategy_map = {
                    "🚀 Auto-Optimize (Recommended)": "auto",
                    "⚡ Llama 3.3 70B (Fast & Balanced)": "llama-3.3-fast",
                    "🧠 Llama 3.3 70B (Quality Focus)": "llama-3.3-quality",
                    "🔄 Mixtral 8x7B (Alternative)": "mixtral-8x7b",
                }
                
                selected_strategy = strategy_map[model_strategy]
                
                with st.spinner(f"🔍 Researching {company_name}..."):
                    progress_bar = st.progress(0)
                    status_container = st.empty()
                    
                    def progress_callback(progress: int, status: str):
                        progress_bar.progress(progress / 100)
                        status_container.info(f"**Status:** {status}")
                    
                    try:
                        result = asyncio.run(run_research(
                            company_name=company_name,
                            depth=depth,
                            model_strategy=selected_strategy,  # ✅ Pass user choice
                            progress_callback=progress_callback
                        ))
                        
                        st.session_state['latest_result'] = result
                        st.session_state['latest_company'] = company_name
                        st.session_state['research_timestamp'] = datetime.now()
                        st.session_state['model_used'] = model_strategy
                        
                        progress_bar.empty()
                        status_container.empty()
                        
                        st.success(f"✅ Research complete for **{company_name}**!")
                        st.info(f"🤖 Model used: {model_strategy}")
                        
                        st.markdown("---")
                        display_results(result, company_name, "new")
                        
                    except Exception as e:
                        st.error(f"❌ Research failed: {str(e)}")
                        st.warning("💡 **Try switching to a different model** in the sidebar if this persists.")
                        st.exception(e)
                        
            except ImportError as e:
                st.error(f"❌ Import failed: {e}")

with tab2:
    st.header("📊 Latest Research Results")
    
    if 'latest_result' in st.session_state:
        company = st.session_state.get('latest_company', 'Unknown')
        result = st.session_state['latest_result']
        timestamp = st.session_state.get('research_timestamp', datetime.now())
        model_used = st.session_state.get('model_used', 'N/A')
        
        st.info(f"📅 **Company:** {company} | **Generated:** {timestamp.strftime('%Y-%m-%d %H:%M')} | **Model:** {model_used}")
        
        display_results(result, company, "latest")
    else:
        st.info("👈 Run a research from the **New Research** tab first")

with tab3:
    st.header("📖 Example Companies")
    
    col1, col2 = st.columns(2)
    
    with col1:
        st.subheader("🚀 Tech Startups")
        st.markdown("• Stripe\n• Notion\n• Figma\n• Linear\n• Vercel")
        
        st.subheader("🤖 AI Companies")
        st.markdown("• OpenAI\n• Anthropic\n• Hugging Face")
    
    with col2:
        st.subheader("💼 B2B SaaS")
        st.markdown("• Salesforce\n• HubSpot\n• Intercom")
        
        st.subheader("🛒 E-commerce")
        st.markdown("• Shopify\n• Square\n• BigCommerce")

st.markdown("---")
st.markdown("<div style='text-align: center; color: #666;'><p><strong>AI Competitor Intelligence</strong> • Powered by Open Source AI</p></div>", unsafe_allow_html=True)
