import streamlit as st
import asyncio
import os
from datetime import datetime
import json
import uuid

# Must be first Streamlit command
st.set_page_config(
    page_title="AI Competitor Intelligence",
    page_icon="🔍",
    layout="wide",
    initial_sidebar_state="expanded"
)

# ========================================
# HELPER FUNCTIONS
# ========================================

def generate_text_report(result: dict, company_name: str) -> str:
    """Generate text format report"""
    
    synthesis = result.get('synthesis', {})
    swot = synthesis.get('swot_analysis', {})
    
    report = f"""
{'='*60}
COMPETITOR INTELLIGENCE REPORT
{'='*60}

Company: {company_name}
Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

{'='*60}
EXECUTIVE SUMMARY
{'='*60}

{synthesis.get('executive_summary', 'N/A')}

{'='*60}
KEY METRICS
{'='*60}

Competitive Score: {synthesis.get('competitive_score', 0)}/100
Financial Health: {synthesis.get('financial_health', {}).get('health_score', 0)}/100
Product-Market Fit: {synthesis.get('product_analysis', {}).get('product_market_fit_score', 0)}/100

{'='*60}
SWOT ANALYSIS
{'='*60}

STRENGTHS:
{chr(10).join(f'  • {s}' for s in swot.get('strengths', ['N/A']))}

WEAKNESSES:
{chr(10).join(f'  • {w}' for w in swot.get('weaknesses', ['N/A']))}

OPPORTUNITIES:
{chr(10).join(f'  • {o}' for o in swot.get('opportunities', ['N/A']))}

THREATS:
{chr(10).join(f'  • {t}' for t in swot.get('threats', ['N/A']))}

{'='*60}
STRATEGIC RECOMMENDATIONS
{'='*60}

{chr(10).join(f'{i}. {r}' for i, r in enumerate(synthesis.get('strategic_recommendations', ['N/A']), 1))}

{'='*60}
END OF REPORT
{'='*60}

Generated by AI Competitor Intelligence
Powered by Open Source AI
"""
    
    return report


def display_results(result: dict, company_name: str, context: str = "main"):
    """Display research results in structured format"""
    
    synthesis = result.get('synthesis', {})
    
    if not synthesis:
        st.warning("⚠️ Synthesis data not available")
        return
    
    # Create unique key for this render
    unique_key = f"{context}_{uuid.uuid4().hex[:8]}"
    
    # Executive Summary
    st.subheader("📋 Executive Summary")
    summary = synthesis.get('executive_summary', 'No summary available')
    st.info(summary)
    
    st.markdown("---")
    
    # Key Metrics Row
    st.subheader("📊 Key Metrics")
    col1, col2, col3 = st.columns(3)
    
    with col1:
        score = synthesis.get('competitive_score', 0)
        st.metric(
            "Competitive Score",
            f"{score}/100",
            help="Overall competitive strength"
        )
    
    with col2:
        health = synthesis.get('financial_health', {})
        health_score = health.get('health_score', 0)
        st.metric(
            "Financial Health",
            f"{health_score}/100",
            help="Financial stability"
        )
    
    with col3:
        product = synthesis.get('product_analysis', {})
        pmf = product.get('product_market_fit_score', 0)
        st.metric(
            "Product-Market Fit",
            f"{pmf}/100",
            help="Product meets market needs"
        )
    
    st.markdown("---")
    
    # Company Overview
    st.subheader("🏢 Company Overview")
    overview = synthesis.get('company_overview', {})
    
    if overview:
        col1, col2 = st.columns(2)
        
        with col1:
            st.markdown("**Background**")
            st.write(overview.get('background', 'N/A'))
        
        with col2:
            st.markdown("**Market Position**")
            st.write(overview.get('market_position', 'N/A'))
        
        st.markdown("**Size & Scale**")
        st.write(overview.get('size_and_scale', 'N/A'))
    
    st.markdown("---")
    
    # SWOT Analysis
    st.subheader("📊 SWOT Analysis")
    swot = synthesis.get('swot_analysis', {})
    
    col1, col2 = st.columns(2)
    
    with col1:
        with st.expander("💪 **Strengths**", expanded=True):
            strengths = swot.get('strengths', [])
            if strengths:
                for s in strengths:
                    st.markdown(f"✅ {s}")
            else:
                st.write("_No data available_")
        
        with st.expander("🎯 **Opportunities**", expanded=True):
            opps = swot.get('opportunities', [])
            if opps:
                for o in opps:
                    st.markdown(f"🔹 {o}")
            else:
                st.write("_No data available_")
    
    with col2:
        with st.expander("⚠️ **Weaknesses**", expanded=True):
            weaknesses = swot.get('weaknesses', [])
            if weaknesses:
                for w in weaknesses:
                    st.markdown(f"⚠️ {w}")
            else:
                st.write("_No data available_")
        
        with st.expander("🚨 **Threats**", expanded=True):
            threats = swot.get('threats', [])
            if threats:
                for t in threats:
                    st.markdown(f"⚡ {t}")
            else:
                st.write("_No data available_")
    
    st.markdown("---")
    
    # Product Analysis
    st.subheader("🎨 Product & Offering Analysis")
    product_analysis = synthesis.get('product_analysis', {})
    
    if product_analysis:
        col1, col2 = st.columns(2)
        
        with col1:
            st.markdown("**Core Offerings**")
            st.write(product_analysis.get('core_offerings', 'N/A'))
            
            st.markdown("**Pricing Strategy**")
            st.write(product_analysis.get('pricing_strategy', 'N/A'))
        
        with col2:
            st.markdown("**Key Differentiators**")
            differentiators = product_analysis.get('differentiators', [])
            if differentiators:
                for d in differentiators:
                    st.markdown(f"• {d}")
            else:
                st.write("_No data available_")
    
    st.markdown("---")
    
    # Financial Health
    st.subheader("💰 Financial Health Assessment")
    financial = synthesis.get('financial_health', {})
    
    if financial:
        st.write(f"**Status:** {financial.get('status', 'Unknown')}")
        st.write(f"**Growth Trajectory:** {financial.get('growth_trajectory', 'Unknown')}")
        
        health_pct = financial.get('health_score', 50)
        st.progress(health_pct / 100)
        st.caption(f"Financial Health Score: {health_pct}/100")
    
    st.markdown("---")
    
    # Strategic Recommendations
    st.subheader("💡 Strategic Recommendations")
    recommendations = synthesis.get('strategic_recommendations', [])
    
    if recommendations:
        for i, rec in enumerate(recommendations, 1):
            st.markdown(f"**{i}.** {rec}")
    else:
        st.write("_No recommendations available_")
    
    st.markdown("---")
    
    # Export Section
    st.subheader("💾 Export & Download")
    
    col1, col2 = st.columns(2)
    
    with col1:
        json_data = json.dumps(result, indent=2)
        st.download_button(
            label="📥 Download JSON",
            data=json_data,
            file_name=f"{company_name.replace(' ', '_')}_research.json",
            mime="application/json",
            use_container_width=True,
            key=f"json_{unique_key}"
        )
    
    with col2:
        text_summary = generate_text_report(result, company_name)
        st.download_button(
            label="📄 Download Report (TXT)",
            data=text_summary,
            file_name=f"{company_name.replace(' ', '_')}_report.txt",
            mime="text/plain",
            use_container_width=True,
            key=f"txt_{unique_key}"
        )


# ========================================
# CHECK API KEY
# ========================================

if "GROQ_API_KEY" not in st.secrets:
    st.error("🔑 **API Key Not Configured**")
    st.markdown("""
    ### Setup Required
    
    The Groq API key is missing from Streamlit Secrets.
    
    **To fix this:**
    1. Go to Streamlit Cloud dashboard
    2. Click on your app → **Settings** → **Secrets**
    3. Add:
    ```toml
    GROQ_API_KEY = "your_groq_api_key_here"
    ```
    4. Get free key at [console.groq.com](https://console.groq.com)
    """)
    st.stop()

os.environ["GROQ_API_KEY"] = st.secrets["GROQ_API_KEY"]

# ========================================
# MAIN APP UI
# ========================================

# Custom CSS
st.markdown("""
<style>
    .main-header {
        font-size: 2.8rem;
        font-weight: bold;
        background: linear-gradient(90deg, #2c5aa0 0%, #1e3a8a 100%);
        -webkit-background-clip: text;
        -webkit-text-fill-color: transparent;
        margin-bottom: 0.5rem;
    }
    .subtitle {
        color: #666;
        font-size: 1.1rem;
        margin-bottom: 1.5rem;
    }
    .model-badge {
        background: #e8f4f8;
        padding: 4px 12px;
        border-radius: 16px;
        font-size: 0.85rem;
        color: #2c5aa0;
    }
</style>
""", unsafe_allow_html=True)

# Title
st.markdown('<h1 class="main-header">🔍 AI Competitor Intelligence</h1>', unsafe_allow_html=True)
st.markdown('<p class="subtitle">Autonomous market research powered by multi-model AI</p>', unsafe_allow_html=True)
st.markdown("---")

# ========================================
# SIDEBAR WITH MODEL SELECTOR
# ========================================

with st.sidebar:
    st.header("⚙️ Settings")
    
    # API Status
    st.success("🔑 API Key: Configured ✅")
    
    st.markdown("---")
    
    # Research Depth
    st.subheader("📊 Research Settings")
    
    depth_option = st.selectbox(
        "Analysis Depth",
        [
            "Quick (2-3 min)",
            "Standard (5-7 min)",
            "Deep (10-15 min)"
        ],
        index=1,
        help="Deeper analysis provides more insights but takes longer"
    )
    
    depth_mapping = {
        "Quick (2-3 min)": "quick",
        "Standard (5-7 min)": "standard",
        "Deep (10-15 min)": "deep"
    }
    depth = depth_mapping[depth_option]
    
    st.markdown("---")
    
    # ========================================
    # MODEL SELECTOR (User Control)
    # ========================================
    
    st.subheader("🤖 AI Model Selection")
    
    model_strategy = st.selectbox(
        "Choose Model",
        [
            "🚀 Auto-Optimize (Recommended)",
            "🧠 Llama 3.3 70B (Best Quality)",
            "⚡ Llama 3.1 8B (Fastest)",
            "📚 Mixtral 8x7B (Long Context)",
            "🔬 Gemma 7B (Alternative)",
        ],
        index=0,
        help="Auto-Optimize uses the best model for each task automatically"
    )
    
    # Model Details
    with st.expander("ℹ️ Model Details", expanded=False):
        if model_strategy == "🚀 Auto-Optimize (Recommended)":
            st.markdown("""
            **🎯 Intelligent Multi-Model Routing**
            
            Uses different models for different tasks:
            
            | Task | Model | Why |
            |------|-------|-----|
            | Quick extraction | Llama 3.1 8B | ⚡ 10x faster |
            | Complex analysis | Llama 3.3 70B | 🧠 Best quality |
            | Long documents | Mixtral 8x7B | 📚 32K context |
            
            **Benefits:**
            - ✅ 40% faster overall
            - ✅ Same high quality
            - ✅ Automatic fallback
            """)
        
        elif model_strategy == "🧠 Llama 3.3 70B (Best Quality)":
            st.markdown("""
            **Model:** `llama-3.3-70b-versatile`
            
            **Specifications:**
            - 🧠 70 billion parameters
            - 🎯 Highest reasoning quality
            - 📊 Best for strategic analysis
            
            **Best for:**
            - Critical business decisions
            - In-depth competitor analysis
            - Executive-level reports
            
            | Speed | Quality |
            |-------|---------|
            | ⭐⭐⭐ Medium | ⭐⭐⭐⭐⭐ Excellent |
            """)
        
        elif model_strategy == "⚡ Llama 3.1 8B (Fastest)":
            st.markdown("""
            **Model:** `llama-3.1-8b-instant`
            
            **Specifications:**
            - ⚡ 8 billion parameters
            - 🚀 500+ tokens/second
            - 🏃 10x faster than 70B
            
            **Best for:**
            - Quick insights
            - High volume research
            - Time-sensitive analysis
            
            | Speed | Quality |
            |-------|---------|
            | ⭐⭐⭐⭐⭐ Fastest | ⭐⭐⭐⭐ Very Good |
            """)
        
        elif model_strategy == "📚 Mixtral 8x7B (Long Context)":
            st.markdown("""
            **Model:** `mixtral-8x7b-32768`
            
            **Specifications:**
            - 📚 32,768 token context window
            - 🔀 Mixture of Experts architecture
            - 🎛️ 8 expert networks
            
            **Best for:**
            - Long documents
            - Detailed analysis
            - Multiple data sources
            
            | Speed | Quality |
            |-------|---------|
            | ⭐⭐⭐⭐ Fast | ⭐⭐⭐⭐ Very Good |
            """)
        
        elif model_strategy == "🔬 Gemma 7B (Alternative)":
            st.markdown("""
            **Model:** `gemma-7b-it`
            
            **Specifications:**
            - 🔬 Google's Gemma model
            - 7 billion parameters
            - Alternative architecture
            
            **Best for:**
            - When other models fail
            - Experimental testing
            - Comparison purposes
            
            | Speed | Quality |
            |-------|---------|
            | ⭐⭐⭐⭐ Fast | ⭐⭐⭐ Good |
            """)
    
    # Helpful tip
    st.caption("💡 **Tip:** If research fails, try switching to a different model")
    
    st.markdown("---")
    
    # Last Research Stats
    if 'latest_result' in st.session_state:
        st.subheader("📈 Last Research")
        
        company = st.session_state.get('latest_company', 'N/A')
        st.write(f"**Company:** {company}")
        
        synthesis = st.session_state['latest_result'].get('synthesis', {})
        score = synthesis.get('competitive_score', 0)
        st.metric("Competitive Score", f"{score}/100")
        
        if 'model_used' in st.session_state:
            model_short = st.session_state['model_used'].split(' ')[1] if ' ' in st.session_state['model_used'] else st.session_state['model_used']
            st.caption(f"Model: {model_short}")
    
    st.markdown("---")
    
    # About Section
    with st.expander("ℹ️ About This Tool"):
        st.markdown("""
        **AI Competitor Intelligence**
        
        Autonomous research system that analyzes:
        - 🌐 Company websites
        - 📱 Social media presence
        - 💰 Financial health
        - 🎨 Product offerings
        - 📊 Market positioning
        
        **Technology:**
        - Multi-model AI routing
        - Real-time web scraping
        - LLM-powered analysis
        
        **100% Free & Open Source**
        """)
    
    st.markdown("---")
    st.caption("Built with ❤️ using open-source AI")

# ========================================
# MAIN CONTENT TABS
# ========================================

tab1, tab2, tab3 = st.tabs(["🎯 New Research", "📊 Latest Results", "📖 Examples"])

# ========================================
# TAB 1: NEW RESEARCH
# ========================================

with tab1:
    st.header("Start New Competitor Research")
    
    col1, col2 = st.columns([3, 1])
    
    with col1:
        company_name = st.text_input(
            "Company Name",
            placeholder="e.g., Stripe, Notion, Figma, OpenAI, Shopify",
            help="Enter the exact company name for best results"
        )
    
    with col2:
        st.write("")  # Spacing
        st.write("")  # Spacing
        start_research = st.button(
            "🚀 Start Research",
            type="primary",
            use_container_width=True
        )
    
    # Example companies
    st.caption("**Try these:** Stripe • Notion • Figma • Linear • Vercel • Supabase • OpenAI")
    
    if start_research:
        if not company_name or len(company_name) < 2:
            st.error("❌ Please enter a valid company name")
        else:
            try:
                from agents.orchestrator import run_research
                
                # Map UI selection to internal strategy
                strategy_map = {
                    "🚀 Auto-Optimize (Recommended)": "auto",
                    "🧠 Llama 3.3 70B (Best Quality)": "llama-3.3-70b",
                    "⚡ Llama 3.1 8B (Fastest)": "llama-3.1-8b",
                    "📚 Mixtral 8x7B (Long Context)": "mixtral-8x7b",
                    "🔬 Gemma 7B (Alternative)": "gemma-7b",
                }
                
                selected_strategy = strategy_map[model_strategy]
                
                # Show current model
                st.info(f"🤖 **Using:** {model_strategy}")
                
                with st.spinner(f"🔍 Researching {company_name}..."):
                    # Progress tracking
                    progress_bar = st.progress(0)
                    status_container = st.empty()
                    
                    def progress_callback(progress: int, status: str):
                        progress_bar.progress(progress / 100)
                        status_container.info(f"**Status:** {status}")
                    
                    try:
                        result = asyncio.run(run_research(
                            company_name=company_name,
                            depth=depth,
                            model_strategy=selected_strategy,
                            progress_callback=progress_callback
                        ))
                        
                        # Store in session state
                        st.session_state['latest_result'] = result
                        st.session_state['latest_company'] = company_name
                        st.session_state['research_timestamp'] = datetime.now()
                        st.session_state['model_used'] = model_strategy
                        
                        # Clear progress
                        progress_bar.empty()
                        status_container.empty()
                        
                        st.success(f"✅ Research complete for **{company_name}**!")
                        
                        # Show model used
                        col1, col2 = st.columns([3, 1])
                        with col1:
                            st.markdown(f"📅 Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}")
                        with col2:
                            st.markdown(f"🤖 Model: {model_strategy.split(' ')[0]}")
                        
                        # Display results
                        st.markdown("---")
                        display_results(result, company_name, context="new_research")
                        
                    except Exception as e:
                        progress_bar.empty()
                        status_container.empty()
                        
                        st.error(f"❌ Research failed: {str(e)}")
                        
                        # Helpful troubleshooting
                        st.warning("""
                        **💡 Troubleshooting Tips:**
                        
                        1. **Try a different model** - Select another option in sidebar
                        2. **Simplify company name** - Use "Stripe" not "Stripe Inc."
                        3. **Check internet** - Ensure stable connection
                        4. **Wait and retry** - API might be temporarily busy
                        """)
                        
                        with st.expander("🔍 Technical Details"):
                            st.exception(e)
                        
            except ImportError as e:
                st.error(f"❌ Failed to import research modules: {e}")
                st.info("Please ensure all agent files are properly uploaded.")

# ========================================
# TAB 2: LATEST RESULTS
# ========================================

with tab2:
    st.header("📊 Latest Research Results")
    
    if 'latest_result' in st.session_state:
        company = st.session_state.get('latest_company', 'Unknown')
        result = st.session_state['latest_result']
        timestamp = st.session_state.get('research_timestamp', datetime.now())
        model_used = st.session_state.get('model_used', 'N/A')
        
        # Info bar
        col1, col2, col3 = st.columns(3)
        with col1:
            st.info(f"📅 **Company:** {company}")
        with col2:
            st.info(f"🕐 **Generated:** {timestamp.strftime('%Y-%m-%d %H:%M')}")
        with col3:
            st.info(f"🤖 **Model:** {model_used.split('(')[0].strip()}")
        
        display_results(result, company, context="latest_results")
        
    else:
        st.info("👈 Run a research from the **New Research** tab first")
        
        st.markdown("""
        ### What you'll get:
        
        - 📋 **Executive Summary** - Key insights at a glance
        - 📊 **SWOT Analysis** - Strengths, Weaknesses, Opportunities, Threats
        - 💰 **Financial Health** - Funding, growth, stability assessment
        - 🎨 **Product Analysis** - Features, pricing, market fit
        - 💡 **Strategic Recommendations** - Actionable next steps
        - 📥 **Export Options** - Download as JSON or TXT
        """)
        
        st.markdown("---")
        
        st.markdown("""
        ### 🤖 Model Selection Tips
        
        | Scenario | Recommended Model |
        |----------|------------------|
        | First time user | 🚀 Auto-Optimize |
        | Need speed | ⚡ Llama 3.1 8B |
        | Critical decision | 🧠 Llama 3.3 70B |
        | Model issues | 🔬 Gemma 7B |
        """)

# ========================================
# TAB 3: EXAMPLES
# ========================================

with tab3:
    st.header("📖 Example Companies & Use Cases")
    
    col1, col2 = st.columns(2)
    
    with col1:
        st.subheader("🚀 Tech Startups")
        st.markdown("""
        **Great for competitive analysis:**
        - **Stripe** - Payment processing
        - **Notion** - Productivity workspace
        - **Figma** - Design collaboration
        - **Linear** - Issue tracking
        - **Vercel** - Web deployment
        - **Supabase** - Backend-as-a-service
        """)
        
        st.subheader("🤖 AI Companies")
        st.markdown("""
        **Understand AI landscape:**
        - **OpenAI** - GPT models
        - **Anthropic** - Claude AI
        - **Hugging Face** - AI community
        - **Replicate** - Model hosting
        - **Stability AI** - Image generation
        """)
    
    with col2:
        st.subheader("💼 B2B SaaS")
        st.markdown("""
        **Enterprise software:**
        - **Salesforce** - CRM leader
        - **HubSpot** - Marketing automation
        - **Intercom** - Customer messaging
        - **Zendesk** - Customer support
        - **Slack** - Team communication
        """)
        
        st.subheader("🛒 E-commerce")
        st.markdown("""
        **E-commerce platforms:**
        - **Shopify** - Online stores
        - **Square** - Payments & POS
        - **BigCommerce** - Enterprise
        - **WooCommerce** - WordPress
        """)
    
    st.markdown("---")
    
    st.subheader("💡 Best Practices")
    
    col1, col2 = st.columns(2)
    
    with col1:
        st.markdown("""
        **For best results:**
        
        1. ✅ Use exact company names
        2. ✅ Start with Auto-Optimize
        3. ✅ Try different models if issues
        4. ✅ Download results for records
        5. ✅ Verify critical data
        """)
    
    with col2:
        st.markdown("""
        **Use cases:**
        
        - 📊 Competitive positioning
        - 💰 Investor due diligence
        - 🎯 Market entry strategy
        - 📈 Feature comparison
        - 💼 Sales battlecards
        """)
    
    st.markdown("---")
    
    st.subheader("🔧 Model Selection Guide")
    
    st.markdown("""
    | Your Need | Best Model | Why |
    |-----------|------------|-----|
    | General research | 🚀 Auto-Optimize | Best of all worlds |
    | Quick insights | ⚡ Llama 3.1 8B | 10x faster |
    | Strategic report | 🧠 Llama 3.3 70B | Deepest analysis |
    | Primary model fails | 📚 Mixtral / 🔬 Gemma | Alternative options |
    """)

# ========================================
# FOOTER
# ========================================

st.markdown("---")
st.markdown("""
<div style='text-align: center; color: #666; padding: 1.5rem 0;'>
    <p><strong>AI Competitor Intelligence</strong></p>
    <p style='font-size: 0.9rem;'>Powered by Groq • Multi-Model AI • 100% Open Source</p>
    <p style='font-size: 0.8rem; color: #999;'>No data stored • Privacy first • Free forever</p>
</div>
""", unsafe_allow_html=True)
